{
 "title": "DD-WRT Router Monitor",
 "description": "DD-WRT Dashboard using SNMP data stored in Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(snmp_scrape_duration_seconds{job=~\"snmp\"}, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssCpuSystem{hostname=~\"$node\"} + ssCpuUser{hostname=~\"$node\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Router Version/Build",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysDescription{hostname=~\"$node\", job=\"snmp\"}  ",
     "legendFormat": "{{sysDescription}}"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (memTotalFree{hostname=~\"$node\"} / memTotalReal{hostname=~\"$node\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Wireless Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(wlInterfaceClientCount{hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Client count per SSID",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wlInterfaceClientCount{hostname=\"$node\"} * on (wlInterfaceName) group_left(wlInterfaceSSID) wlInterfaceSSID{hostname=\"$node\"}",
     "legendFormat": "{{wlInterfaceSSID}} ({{wlInterfaceName}})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemUpTime{hostname=~\"$node\", job=\"snmp\"}/100"
    }
   ]
  },
  {
   "title": "Wireless Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutOctets{ifDescr=~\"eth1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Outgoing (2.4 GHz / eth1)"
    },
    {
     "expr": "rate(ifInOctets{ifDescr=~\"eth1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Incoming (2.4 GHz / eth1)"
    },
    {
     "expr": "rate(ifOutOctets{ifDescr=~\"eth2\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Outgoing (5 GHz / eth2)"
    },
    {
     "expr": "rate(ifInOctets{ifDescr=~\"eth2\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Incoming (5 GHz / eth2)"
    },
    {
     "expr": "rate(ifInOctets{ifDescr=~\"wl0.1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Incoming (Guest 2.4 GHz / wl0.1)"
    },
    {
     "expr": "rate(ifOutOctets{ifDescr=~\"wl0.1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Outgoing (Guest 2.4 GHz / wl0.1)"
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status)(rate(ifInOctets{ifDescr=\"vlan2\", hostname=~\"$node\", job=\"snmp\"}[1m])) * 8",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status)(irate(ifOutOctets{ifDescr=\"vlan2\", hostname=~\"$node\", job=\"snmp\"}[1m])) * 8",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Wired Traffic (eth0)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutOctets{ifDescr=~\"eth0\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "rate(ifInOctets{ifDescr=~\"eth0\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Incoming"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectionsTCP{hostname=\"$node\"}+connectionsUDP{hostname=\"$node\"}+connectionsICMP{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connectionsTCP{hostname=\"$node\"}",
     "legendFormat": "TCP"
    },
    {
     "expr": "connectionsUDP{hostname=\"$node\"}",
     "legendFormat": "UDP"
    },
    {
     "expr": "connectionsICMP{hostname=\"$node\"}",
     "legendFormat": "ICMP"
    }
   ]
  },
  {
   "title": "LAN Traffic (vlan1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutOctets{ifDescr=\"vlan1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "rate(ifInOctets{ifDescr=\"vlan1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "WAN Traffic (vlan2)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(irate(ifOutOctets{ifDescr=\"vlan2\", hostname=~\"$node\", job=\"snmp\"}[5m])) * 8",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "sum by(status)(irate(ifInOctets{ifDescr=\"vlan2\", hostname=~\"$node\", job=\"snmp\"}[5m])) * 8",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "VPN Tunnel Traffic (tun1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutOctets{ifDescr=~\"tun1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "rate(ifInOctets{ifDescr=~\"tun1\", hostname=~\"$node\", job=\"snmp\"}[5m]) * 8",
     "legendFormat": "Incoming"
    }
   ]
  },
  { "title": "Load / CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Num CPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ssCpuNumCpus{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "System Load (1/5/15 Mins)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "laLoadInt{laNames=\"Load-1\", hostname=~\"$node\"}/100",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{laNames=\"Load-5\", hostname=~\"$node\"}/100",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{laNames=\"Load-15\", hostname=~\"$node\"}/100",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "CPU Temperature (°C)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cpuTemperature{hostname=\"$node\"}/10"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpuTemperature{hostname=\"$node\"}/10",
     "legendFormat": "°C"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ssCpuSystem{hostname=~\"$node\"}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{hostname=~\"$node\"}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuIdle{hostname=~\"$node\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 45 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{hostname=~\"$node\"}-memTotalFree{hostname=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "memTotalFree{hostname=~\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "memTotalSwap{hostname=~\"$node\"}",
     "legendFormat": "Swap"
    }
   ]
  }
 ]
}